import { Product, ProductVariation } from "@/types/product.interface";

// Main product data from your WooCommerce API
export const products: Product[] = [
  {
    id: 18,
    name: "Dress Shirt / Forest Green",
    slug: "dress-shirt-forest-green",
    permalink: "https://ndtien142.xyz/product/dress-shirt-forest-green/",
    date_created: "2019-01-16T20:01:54",
    date_created_gmt: "2019-01-16T13:01:54",
    date_modified: "2025-03-24T23:15:41",
    date_modified_gmt: "2025-03-24T16:15:41",
    type: "variable",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description:
      '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>\n<h2>Details</h2>\n<div class="ProductItem-details-excerpt" data-content-field="excerpt">\n<ul>\n<li>100% Cotton</li>\n<li>Machine wash cold</li>\n<li>Environmentally Sustainable</li>\n</ul>\n</div>\n',
    sku: "woo-album",
    price: "140000",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 1,
    download_expiry: 1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: false,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 43,
        name: "Shirt",
        slug: "shirt",
      },
      {
        id: 37,
        name: "Tops",
        slug: "tops",
      },
    ],
    tags: [],
    images: [
      {
        id: 203,
        date_created: "2022-01-28T08:47:04",
        date_created_gmt: "2022-01-28T01:47:04",
        date_modified: "2022-01-28T08:47:04",
        date_modified_gmt: "2022-01-28T01:47:04",
        src: "https://ndtien142.xyz/wp-content/uploads/2019/01/shirt-green.jpg",
        name: "shirt-green",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "Color",
        position: 0,
        visible: true,
        variation: true,
        options: ["Green", "Black"],
      },
      {
        id: 0,
        name: "Size",
        slug: "Size",
        position: 1,
        visible: true,
        variation: true,
        options: ["M", "L", "XL"],
      },
    ],
    default_attributes: [],
    variations: [647, 648, 649, 650, 651, 652],
    grouped_products: [],
    menu_order: 4,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi>140.000&nbsp;<span class="woocommerce-Price-currencySymbol">&#8363;</span></bdi></span> &ndash; <span class="woocommerce-Price-amount amount"><bdi>150.000&nbsp;<span class="woocommerce-Price-currencySymbol">&#8363;</span></bdi></span>',
    related_ids: [15, 8, 14, 6, 513],
    meta_data: [
      {
        id: 3464,
        key: "_wpb_vc_js_status",
        value: "true",
      },
      {
        id: 3465,
        key: "_wpb_post_custom_layout",
        value: "default",
      },
    ],
    stock_status: "instock",
    has_options: true,
    post_password: "",
    global_unique_id: "",
    brands: [],
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products",
        },
      ],
    },
  },
];

// Product variations data from your WooCommerce API
export const productVariations: ProductVariation[] = [
  {
    id: 652,
    type: "variation",
    date_created: "2025-03-14T14:40:04",
    date_created_gmt: "2025-03-14T07:40:04",
    date_modified: "2025-03-14T14:41:28",
    date_modified_gmt: "2025-03-14T07:41:28",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Black&attribute_size=XL",
    sku: "woo-album",
    global_unique_id: "",
    price: "150000",
    regular_price: "150000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 203,
      date_created: "2022-01-28T08:47:04",
      date_created_gmt: "2022-01-28T01:47:04",
      date_modified: "2022-01-28T08:47:04",
      date_modified_gmt: "2022-01-28T01:47:04",
      src: "https://ndtien142.xyz/wp-content/uploads/2019/01/shirt-green.jpg",
      name: "shirt-green",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Black",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "XL",
      },
    ],
    menu_order: 6,
    meta_data: [],
    name: "Black, XL",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/652",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
  {
    id: 651,
    type: "variation",
    date_created: "2025-03-14T14:40:04",
    date_created_gmt: "2025-03-14T07:40:04",
    date_modified: "2025-03-14T14:41:28",
    date_modified_gmt: "2025-03-14T07:41:28",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Black&attribute_size=L",
    sku: "woo-album",
    global_unique_id: "",
    price: "150000",
    regular_price: "150000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 203,
      date_created: "2022-01-28T08:47:04",
      date_created_gmt: "2022-01-28T01:47:04",
      date_modified: "2022-01-28T08:47:04",
      date_modified_gmt: "2022-01-28T01:47:04",
      src: "https://ndtien142.xyz/wp-content/uploads/2019/01/shirt-green.jpg",
      name: "shirt-green",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Black",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "L",
      },
    ],
    menu_order: 5,
    meta_data: [
      {
        id: 3629,
        key: "woosw_count",
        value: "1",
      },
      {
        id: 3630,
        key: "woosw_add",
        value: "1741952878",
      },
    ],
    name: "Black, L",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/651",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
  {
    id: 650,
    type: "variation",
    date_created: "2025-03-14T14:40:04",
    date_created_gmt: "2025-03-14T07:40:04",
    date_modified: "2025-03-14T14:41:27",
    date_modified_gmt: "2025-03-14T07:41:27",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Black&attribute_size=M",
    sku: "woo-album",
    global_unique_id: "",
    price: "150000",
    regular_price: "150000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 203,
      date_created: "2022-01-28T08:47:04",
      date_created_gmt: "2022-01-28T01:47:04",
      date_modified: "2022-01-28T08:47:04",
      date_modified_gmt: "2022-01-28T01:47:04",
      src: "https://ndtien142.xyz/wp-content/uploads/2019/01/shirt-green.jpg",
      name: "shirt-green",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Black",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "M",
      },
    ],
    menu_order: 4,
    meta_data: [],
    name: "Black, M",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/650",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
  {
    id: 649,
    type: "variation",
    date_created: "2025-03-14T14:40:04",
    date_created_gmt: "2025-03-14T07:40:04",
    date_modified: "2025-03-14T14:41:27",
    date_modified_gmt: "2025-03-14T07:41:27",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Green&attribute_size=XL",
    sku: "woo-album",
    global_unique_id: "",
    price: "150000",
    regular_price: "150000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 203,
      date_created: "2022-01-28T08:47:04",
      date_created_gmt: "2022-01-28T01:47:04",
      date_modified: "2022-01-28T08:47:04",
      date_modified_gmt: "2022-01-28T01:47:04",
      src: "https://ndtien142.xyz/wp-content/uploads/2019/01/shirt-green.jpg",
      name: "shirt-green",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Green",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "XL",
      },
    ],
    menu_order: 3,
    meta_data: [],
    name: "Green, XL",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/649",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
  {
    id: 648,
    type: "variation",
    date_created: "2025-03-14T14:40:03",
    date_created_gmt: "2025-03-14T07:40:03",
    date_modified: "2025-03-15T15:02:16",
    date_modified_gmt: "2025-03-15T08:02:16",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Green&attribute_size=L",
    sku: "woo-album",
    global_unique_id: "",
    price: "140000",
    regular_price: "140000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 237,
      date_created: "2022-01-31T07:19:21",
      date_created_gmt: "2022-01-31T00:19:21",
      date_modified: "2022-01-31T07:19:21",
      date_modified_gmt: "2022-01-31T00:19:21",
      src: "https://ndtien142.xyz/wp-content/uploads/2022/01/vecteezy_black-sweater-hanging-on-hanger__773.jpg",
      name: "vecteezy_black-sweater-hanging-on-hanger__773",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Green",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "L",
      },
    ],
    menu_order: 2,
    meta_data: [],
    name: "Green, L",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/648",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
  {
    id: 647,
    type: "variation",
    date_created: "2025-03-14T14:40:03",
    date_created_gmt: "2025-03-14T07:40:03",
    date_modified: "2025-03-15T15:02:16",
    date_modified_gmt: "2025-03-15T08:02:16",
    description: "",
    permalink:
      "https://ndtien142.xyz/product/dress-shirt-forest-green/?attribute_color=Green&attribute_size=M",
    sku: "woo-album",
    global_unique_id: "",
    price: "140000",
    regular_price: "140000",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    status: "publish",
    purchasable: true,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    weight: "2",
    dimensions: {
      length: "1",
      width: "3",
      height: "2",
    },
    shipping_class: "",
    shipping_class_id: 0,
    image: {
      id: 246,
      date_created: "2022-01-31T07:19:40",
      date_created_gmt: "2022-01-31T00:19:40",
      date_modified: "2022-01-31T07:19:40",
      date_modified_gmt: "2022-01-31T00:19:40",
      src: "https://ndtien142.xyz/wp-content/uploads/2022/01/vecteezy_t-shirt-hanging-with-wood-hanger__920.jpg",
      name: "vecteezy_t-shirt-hanging-with-wood-hanger__920",
      alt: "",
    },
    attributes: [
      {
        id: 0,
        name: "Color",
        slug: "color",
        option: "Green",
      },
      {
        id: 0,
        name: "Size",
        slug: "size",
        option: "M",
      },
    ],
    menu_order: 1,
    meta_data: [],
    name: "Green, M",
    parent_id: 18,
    _links: {
      self: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations/647",
          targetHints: {
            allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
          },
        },
      ],
      collection: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18/variations",
        },
      ],
      up: [
        {
          href: "https://ndtien142.xyz/wp-json/wc/v3/products/18",
        },
      ],
    },
  },
];
